### ISSUE TITLE
Error: PDFJS is not defined

### ISSUE THREAD

**Issue by Paul75** [hallysonh/ngx-imageviewer#16]
Hello,

I've got this error in console : 
PDFJS is not defined
with the last version of pdf-dist...
only works with 2.0.288...

Thanks

**Comment by jacekk** [comment]
@Paul75 https://github.com/hallysonh/ngx-imageviewer#support-pdf - have you extended `scripts` in `.angular-cli.json` ?

**Comment by Paul75** [comment]
yes I add scripts into a .angular-cli.json ....

**Comment by Paul75** [comment]
Hello,

To works with last version of 2.0.288 I change the pdf.loader.ts: 

```
declare var require: any;
const PDFJS = require('pdfjs-dist');
```

and in constructor : 
```
if (!PDFJS.workerSrc) {
      PDFJS.workerSrc = './node_modules/pdfjs-dist/build/pdf.worker.js';
    }

```

**Comment by hallysonh** [comment]
The newest version deal with this global variable issue. You must just include the code below in your angular.json:

```json
...
  "scripts": [
    {
      "input": "node_modules/pdfjs-dist/build/pdf.min.js"
    }, {
      "input": "node_modules/pdfjs-dist/build/pdf.worker.min.js"
    }
  ],
...
```

**Comment by rajppd** [comment]
Hi,
I have done all installs and script additions to Angular CLI as given. 
Images are properly loading. But pdf files show this error. 

ReferenceError: pdfjsLib is not defined at new PdfResourceLoader (hallysonh-ngx-imageviewer.js:450)
Any help please...
