### ISSUE TITLE
Module Import Error

### ISSUE THREAD

**Issue by paritoshgpt1** [hallysonh/ngx-imageviewer#2]
Hi, I am getting this error

 Unexpected value 'ImageViewerModule' imported by the module 'AppModule'. Please add a @NgModule annotation.

Could you please check it?

Additional Details:

I am running angular 4.
I tried running previous versions of the package as well. No success.

**Comment by Kapcash** [comment]
I'm having a similar issue, importing the project into my module : 

`Metadata version mismatch for module /home/asi/dev/Sturno/portail-ged/portail-ged-web/web/node_modules/@hallysonh/ngx-imageviewer/node_modules/@angular/core/core.d.ts, found version 4, expected 3, resolving symbol ImageViewerModule in /home/asi/dev/Sturno/portail-ged/portail-ged-web/web/node_modules/@hallysonh/ngx-imageviewer/ngx-imageviewer.d.ts, resolving symbol ImageViewerModule in /home/asi/dev/Sturno/portail-ged/portail-ged-web/web/node_modules/@hallysonh/ngx-imageviewer/ngx-imageviewer.d.ts`

Looks like it doesn't support Angular 4.

**Comment by hallysonh** [comment]
Sorry, it is actually working on Angular 5+. I updated the README file.
