### ISSUE TITLE
ngx-imageviewer

### ISSUE THREAD

**Issue by jestin89** [hallysonh/ngx-imageviewer#3]
How to get local file path in ngx-imageviewer? pls help me!

**Comment by hallysonh** [comment]
I did not undestand. If you want to preview a local file just pass the File object to src property, as you can see [here](ngx-imageviewer/src/app/routes/sourcefile/sourcefile.component.html). If you want to get the url reference of a File object use `URL.createObjectURL(file)` to create a temporary url for your file.
