### ISSUE TITLE
Choose the position of the buttons.

### ISSUE THREAD

**Issue by maiconprange** [hallysonh/ngx-imageviewer#9]
Is it possible to choose the position of the buttons? I need to fix them at the bottom of the image viewer.

**Comment by hallysonh** [comment]
In the current implementation, it is not possible. But I am planning to improve to look and feel of the component. So, in this improvement, I will try to add some button layout options.

**Comment by maiconprange** [comment]
Ok, i'll wait for this implemetation, tnks.
